### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ghost** [MorpheusLev/IPTV#1]
Hey man. I’m sorry that I opened an issue but I really wanted your help on something since I cant find the answer anywhere. So there is my question: I created a txt file with my list in it, then I converted it to m3u with VLC media player, and now I’m trying to find a way to make an online link of my playlist. Its really weird that I couldn’t find a straight answer anywhere. I hope you can help me. Thank you in advance.

**Comment by MorpheusLev** [comment]
You need to upload into your repository
